import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Main from "../components/Main";
import { useMoralis } from "react-moralis";

const supportedChains = ["31337", "421613"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* <Main className="p-8" /> */}
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <Main className="p-8" /> 
            </div>
          ) : (
            <div>{`Please switch to a supported network. We currently only support Arbitrum's testnet (Goerli) local networks through Hardhat.`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    </div>
  );
}
